SyntaxSentinels/SyntaxSentinels

docs/SRS-Volere/Makefile
=> chore: Add makefile to SRS-Volere

docs/SRS-Volere/SRS.pdf, docs/SRS-Volere/SRS.tex
[SS-34](https://github.com/lilweege/SyntaxSentinels/issues/34)
+semver:patch
=> feat: Add security requirements

docs/SRS-Volere/SRS.tex
[SS-79](https://github.com/lilweege/SyntaxSentinels/issues/79)
+semver:feature
=> feat: add section for ideas for solution

docs/SRS-Volere/SRS.tex
[SS-20](https://github.com/lilweege/SyntaxSentinels/issues/20)
+semver:patch
=> fix: User Business section corrected to intended definition of template

docs/SRS-Volere/SRS.pdf, docs/SRS-Volere/SRS.tex
=> fix: Spell checking, grammar fixes, and formatting

docs/SRS-Volere/SRS.tex
[SS-80](https://github.com/lilweege/SyntaxSentinels/issues/80)
+semver:patch
=> fix: Some final edits for the reflection

docs/HazardAnalysis/HazardAnalysis.tex
[SS-94](https://github.com/lilweege/SyntaxSentinels/issues/94)
+semver:feature
=> feat: add introduction to hazard analysis

docs/SRS-Volere/SRS.pdf, docs/SRS-Volere/SRS.tex
=> fix: Fix traceability labels for requirements

docs/SRS-Volere/SRS.pdf, docs/SRS-Volere/SRS.tex
[SS-110](https://github.com/lilweege/SyntaxSentinels/issues/110)
+semver:patch
=> fix: Peer Review 110 - addressed ambiguity with thresholds

docs/SRS-Volere/SRS.pdf, docs/SRS-Volere/SRS.tex
[SS-28](https://github.com/lilweege/SyntaxSentinels/issues/28)
+semver:patch
=> Fix: SS-28 - modified FR1 and added in edit for PR-SL1

docs/projMngmnt/Makefile
=> chore: Add makefile for projMngmnt

docs/projMngmnt/POC_Team_Contrib.tex
[SS-187](https://github.com/SyntaxSentinels/SyntaxSentinels/issues/187)
+semver:patch
=> feat: Team meeting attendance for team contrib

.github/pull_request_template.md
Update the issue template so that linked issues are automatically closed when the PR is merged. Check out https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue for more information.
+semver:patch
=> chore: Change issue template to close linked issues

docs/Design/SoftArchitecture/MG.tex
=> reviewed and extracted abbreviations

docs/Design/SoftDetailedDes/MIS.tex
Resolves [SS-238](https://github.com/SyntaxSentinels/SyntaxSentinels/issues/238)
+semver:patch
=> feat: add intro

docs/Design/SoftArchitecture/MG.tex
Resolves [SS-231](https://github.com/SyntaxSentinels/SyntaxSentinels/issues/231)
None
+semver:patch
=> fix/SS-231 - fixed hierarchy for behaviour-hiding and software decision modules

docs/Design/SoftDetailedDes/MIS.tex
=> fix/SS-239 - fixed module decomposition table in MIS

src/.gitignore, src/README.md, src/backend/.gitignore, src/backend/app.py, src/backend/constants/env_variables.py, src/backend/errors/error_content.py, src/backend/errors/exceptions.py, src/backend/middleman/auth0.py, src/backend/middleman/logger.py, src/backend/requirements.txt, src/backend/routes/private.py, src/backend/routes/public.py
=> feat: add boilerplate for auth0 and logging

src/frontend/src/App.tsx, src/frontend/src/components/Features.tsx, src/frontend/src/components/Navbar.tsx, src/frontend/src/pages/Home.tsx, src/frontend/src/pages/Index.tsx
=> feat: add auth0 to frontend

src/frontend/README.md
=> feat: add frontend readme

src/frontend/src/components/Navbar/Navbar.tsx
=> fix: possible fix for logout issue going to localhost on dev

src/frontend/index.html, src/frontend/package-lock.json, src/frontend/package.json, src/frontend/src/components/UploadBox.tsx, src/frontend/src/pages/Home/AnalyzeFiles.css, src/frontend/src/pages/Home/AnalyzeFiles.tsx, src/frontend/src/pages/Home/UploadResults.css, src/frontend/src/pages/Home/UploadResults.tsx, src/frontend/src/pages/Results.tsx
=> fix: results page

src/frontend/src/components/UploadBox.tsx
=> fix: analyze mode fix

test/FrogJump/FrogJumpBU_original.py, test/FrogJump/FrogJumpTD_original.py, test/FrogJump/FrogJumpTD_spacing+no-op.py, test/FrogJump/FrogJumpTD_spacing.py, test/NumberOfIslands/NumIslands_dfs.py, test/NumberOfIslands/NumIslands_dfs_directions.py, test/NumberOfIslands/NumIslands_dfs_iterative.py, test/NumberOfIslands/NumIslands_dfs_iterative_while.py, test/NumberOfIslands/NumIslands_dfs_visitedset.py, test/NumberOfPaths/NumPath_bottomup_optimized_reverse.py, test/NumberOfPaths/NumPath_bottomup_while+ones.py, test/NumberOfPaths/NumPath_topdown_directions.py, test/NumberOfPaths/NumPaths_bottomup.py, test/NumberOfPaths/NumPaths_bottomup_optimized.py, test/NumberOfPaths/NumPaths_bottomup_while.py, test/NumberOfPaths/NumPaths_topdown.py, test/TwoSum/TwoSum_bruteforce.py, test/TwoSum/TwoSum_bruteforce2.py, test/TwoSum/TwoSum_hashmap.py, test/TwoSum/TwoSum_hashmap2.py, test/TwoSum/TwoSum_twopointer.py, test/TwoSum/TwoSum_twopointer2.py
=> created test samples four problems

src/backend/.gitignore, src/backend/README.md, src/backend/app.py, src/backend/controller/compute.py, src/backend/errors/error_content.py, src/backend/middleware/logger.py, src/backend/requirements.txt, src/server/constants/envConstants.js, src/server/controllers/uploadController.js
=> feat: move python script to a server

src/frontend/src/pages/Results.tsx, src/server/controllers/uploadController.js
=> Feat: Threshold slider

src/frontend/src/pages/Results.tsx
=> fix: add error messaging to results page

src/frontend/src/pages/Results.tsx
=> fix: pagination

docs/VnVReport/VnVReport.tex
Resolves [SS-338](https://github.com/SyntaxSentinels/SyntaxSentinels/issues/338)
+semver:patch
=> feat: add comparison to existing solutions

docs/VnVReport/VnVReport.tex
=> Feat: Changes due to testing

docs/VnVReport/VnVReport.tex
Resolves [SS-336](https://github.com/SyntaxSentinels/SyntaxSentinels/issues/XXXX)
+semver:patch
=> Tests for functional requirements done

docs/VnVReport/VnVReport.tex
Resolves [SS-335](https://github.com/SyntaxSentinels/SyntaxSentinels/issues/XXXX)
+semver:patch
=> Added abbreviations

docs/VnVReport/VnVReport.tex
Resolves [SS-334](https://github.com/SyntaxSentinels/SyntaxSentinels/issues/334)
+semver:patch
=> feat: VnVReport Revision History

docs/VnVReport/VnVReport.tex
Resolves [SS-337](https://github.com/SyntaxSentinels/SyntaxSentinels/issues/337)
No
+semver:patch
=> Non-functional requirement tests evaluated

docs/VnVReport/VnVReport.tex
Resolves [SS-342](https://github.com/SyntaxSentinels/SyntaxSentinels/issues/342)
No
+semver:patch
=> identical traceability from original plan

docs/VnVReport/VnVReport.tex
Resolves [SS-345](https://github.com/SyntaxSentinels/SyntaxSentinels/issues/345)
no
+semver:patch
=> reflection from entire team

docs/projMngmnt/Final_Team_Contrib.tex
=> feat: add template and commits

docs/projMngmnt/Final_Team_Contrib.tex
=> feat: Re-add new sections

docs/projMngmnt/Final_Team_Contrib.tex
=> feat: lecture attendence and trigger items for team contrib

docs/projMngmnt/Final_Team_Contrib.tex
=> meetings and meeting explanation done

docs/projMngmnt/Final_Team_Contrib.tex
=> final read over done

src/frontend/package-lock.json, src/frontend/package.json, src/frontend/src/pages/Results.tsx
=> feat: download report

src/README.md, src/server/controllers/resultsController.js, src/server/controllers/uploadController.js
=> feat: add user guide and minor fixes

docs/SRS-Volere/SRS.tex
=> fixed spacing issues

docs/Design/SoftArchitecture/MG.tex, docs/SRS-Volere/SRS.tex, docs/VnVPlan/VnVPlan.tex, docs/VnVReport/VnVReport.tex
Resolves [SS-402](https://github.com/SyntaxSentinels/SyntaxSentinels/issues/402)
+semver:patch
=> chore: Change Zero-Data-Retention (ZDR) policy

docs/Common.tex, docs/Design/SoftArchitecture/MG.tex, docs/Design/SoftDetailedDes/MIS.tex, docs/VnVPlan/VnVPlan.tex, docs/VnVReport/VnVReport.tex, src/frontend/src/components/Features.test.tsx, src/frontend/src/components/Features.tsx, src/frontend/src/components/Navbar/Navbar.test.tsx, src/frontend/src/components/Navbar/Navbar.tsx, src/frontend/src/pages/GetStarted/Index.test.tsx, src/frontend/src/pages/GetStarted/Index.tsx, src/server/types/errorContent.js
=> fix: Fix typos

docs/ReflectAndTrace/ReflectAndTrace.tex
Resolves [SS-391](https://github.com/SyntaxSentinels/SyntaxSentinels/issues/391)
+semver:patch
=> 6.3, 6.4 done

docs/ReflectAndTrace/ReflectAndTrace.tex
Resolves [SS-392](https://github.com/SyntaxSentinels/SyntaxSentinels/issues/392)
+semver:patch
=> Section 7 complete

docs/ReflectAndTrace/ReflectAndTrace.tex
=> Feat: Section 6.1 and 6.2

src/frontend/src/components/JobsTable.tsx
=> fix: remove delete text

docs/ReflectAndTrace/ReflectAndTrace.tex
Resolves [SS-387](https://github.com/SyntaxSentinels/SyntaxSentinels/issues/387)
Resolves [SS-393](https://github.com/SyntaxSentinels/SyntaxSentinels/issues/393)
+semver:patch
=> feat: ReflectandTrace sections 3 and 4

docs/HazardAnalysis/HazardAnalysis.tex
=> final revision of hazard analysis to reflect current project
